### ISSUE TITLE
Inconsistent search results in v1.4.20

### ISSUE THREAD

**Issue by dme-development** [RediSearch/RediSearch#1045]
We have a Redis setup where we have one master and two slaves. In order to test a previous issue with Redis crashing, we upgraded one of both slaves to v1.4.20, the other one is running 1.4.16.

Now when I do the same wildcard search on both slaves, I get different inconsistent results:
```
redis1.4.16:6379> FT.SEARCH idxCachedAuctionItem "*" LIMIT 0 0
1) (integer) 8224

redis1.4.20:6379> FT.SEARCH idxCachedAuctionItem "*" LIMIT 0 0
1) (integer) 497
```

I'm sure that the last searchresult is wrong, because when I do a more specific query on that same instance, I get more results then the total when doing the wildcard search, eg:
```
redis1.4.20:6379> FT.SEARCH idxCachedAuctionItem "@Make:Audi" LIMIT 0 0
1) (integer) 791
```

I believe this is a new bug introduced in the latest release.

**Comment by dme-development** [comment]
After dropping & recreating the index, the results seem ok again. 
Could this behaviour be caused because the RediSearch module was upgraded only on one slave?

Is there any way to detect master slave out of sync issues on the index? And when they occur, get them in sync again without dropping and recreating the index?

**Comment by mnunberg** [comment]
I cannot see why the master and slave would be out of sync in this scenario, however,

>
I'm sure that the last searchresult is wrong, because when I do a more specific query on that same instance, I get more results then the total when doing the wildcard search, eg:
```
redis1.4.20:6379> FT.SEARCH idxCachedAuctionItem "@Make:Audi" LIMIT 0 0
1) (integer) 791
```
 is wrong. The asterisk query might be limited by `MAXEXPANSIONS` and would therefore not necessarily include `Audi` in the expanded term list.

I went over the changelog between the two versions (1.4.16 and 1.4.20) and could not find anything which would account for the difference in behavior observed. I would suggest if possible to upgrade to the 1.6.5 if possible and see if this fixes anything.

I would in general suggest that all nodes in a configuration be running the same version of RediSearch, but I cannot find anything to account for the differences, again. I would also verify that all nodes are indeed running with the same module arguments.

**Comment by MeirShpilraien** [comment]
@dme-development did you run the same query on master? what is the result? We had an issue where ft.delete was not replicated to slave and we only fixed it on 1.4.19 so I believe your old version slave was not sync with the master and your new version slave was sync. It is also explain why after recreating the index the problem was solved.

The differences in the results between the specific query and the more general one could definitely be MAXEXPANSIONS or TIMEOUT. If you have a way to reproduce it then we can verify..

**Comment by dme-development** [comment]
@MeirShpilraien when I perform the same request on master & slaves now:
MASTER
redis1.4.11:6379> FT.SEARCH idxCachedAuctionItem "*" LIMIT 0 0
1) (integer) 5990

SLAVE 1
redis1.4.16:6379> FT.SEARCH idxCachedAuctionItem "*" LIMIT 0 0
1) (integer) 14760

SLAVE 2
redis1.4.20:6379> FT.SEARCH idxCachedAuctionItem "*" LIMIT 0 0
1) (integer) 11845

Please note that master is even running an older version. 
Can this also be related to the fact that both slaves keep crashing several times per day and that replication is not happening when those crashes occur?

About the MAXEXPANSIONS: what would we a suitable number to set without affecting performance? I see default is 200? Can we just double it without causing issues?

**Comment by MeirShpilraien** [comment]
@dme-development as I said we have a bug that ft.del is not replicated, this bug is on master so the master does not replicates the ft.del commands to slave. You need to upgrade the master to solve it.

Regarding the MAXEXPANSIONS, the more you increase the worst the performance will get (and you will be able to perform less queries per second). So it really depends on your latency and throughput goals. I suggest you will try with some different numbers and see what works best for you.

**Comment by dme-development** [comment]
Thanks for the comments. Upgraded all three instances to v1.4.20 and now the results seem aligned. Closing this issue.
