### ISSUE TITLE
Support for bitvector?

### ISSUE THREAD

**Issue by lumina7** [RediSearch/RediSearch#1133]
Hello, 
Thank you for RediSearch, absolutely great :)

I am curious why there is no bitvector field support for RediSearch?
First space wise, and would it not be faster/ use less cpu cycle than TAG?

I can see it very usefull in some cases.

**Comment by mnunberg** [comment]
We use inverted indexes, and because of this, there is minimal overhead when actually performing searches for tag fields

**Comment by lumina7** [comment]
ok, so I can just stuff my tags fields.

Does using multiple tag fields creates multiple keys or is it better to stuff one tag field with many many items?

**Comment by mnunberg** [comment]
It depends on how many dimensions you'd like to match. I'd say that it would be better if you keep your tags in a single field unless you have some kind of application logic that dictates otherwise.

In any event, a search for multiple tag terms always results in a union search, regardless of whether they exist in a single field or multiple fields.

**Comment by lumina7** [comment]
`An entire tag field index resides in a single Redis key and doesn't have a key per term as the full-text one.`

Let's say I have 1 million items in my index.
If I use one tag field, then thats a 1 million key overhead. 2 tags field 2 millions keys? and so on?

**Comment by mnunberg** [comment]
In inverted indexes, the number of index keys which exist in the database are dependent on the *cardinality* of terms (basically, how many unique terms exist in the database) rather than the number of documents containing that term. RediSearch is designed for low-moderate cardinality and high document count.

In normal full text fields, we create a new key (i.e. an internal redis key) for every unique term. This is not an issue for full text search in human language, since any language might have, at most, several hundred thousand words ("terms").

However, tags might contain programmatic identifiers (for example, a UUID) of which there might be a high cardinality. Because of this, tag indexes internally are a single redis key (per schema field), and internally contain a dictionary mapping tag values to the documents containing them.

@K-Jo we should probably address that bit in the documentation.

**Comment by lumina7** [comment]
Ok, much clearer. Excellent 👍 
Thank you.
