### ISSUE TITLE
Error while cloning the git repo

### ISSUE THREAD

**Issue by ksvnix** [RediSearch/RediSearch#1244]
git clone --recursive https://github.com/RediSearch/RediSearch.git
Cloning into 'RediSearch'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (34/34), done.
fatal: pack has bad object at offset 1471143: inflate returned -5
fatal: index-pack failed

**Comment by gkorland** [comment]
@ksvnix on which OS are you running? it seems like a git issue and not RediSearch issue.

**Comment by ksvnix** [comment]
CentOS Linux release 8.1.1911 / 4.18.0-147.8.1.el8_1.x86_64
git-2.18.2-2.el8_1.x86_64

Used this doc: https://oss.redislabs.com/redisearch/Quick_Start.html

Also manually dowloaded latest release - https://github.com/RediSearch/RediSearch/archive/v1.6.13.zip - can't be installed:

[root@centos8 RediSearch-1.6.13]# make build
fatal: not a git repository (or any of the parent directories): .git
Makefile:76: /rules: No such file or directory
make: * No rule to make target '/rules'.  Stop.

It seems like something wrong?

Thanks in advance!

**Comment by ashtul** [comment]
@rafie 
This seems to be related to `readies`

**Comment by rafie** [comment]
@ksvnix RediSearch repo has submodules. Thus your best chance of building it is by cloning from github, as you did in the first place (note the `--recursive` switch - this is virtually the same as going `git  submodule update --init --recirsive`), except that the git operation failed, probably due to a network condition.
When downloading the archive (rather than cloning), one doesn't actually get a working git repo, thus submodules will not be fetched and the build will fail.
My suggestion is to get over the `git clone` problem and proceed with the build according to the docs.

**Comment by gkorland** [comment]
@ksvnix did you manage to build? can the issue be closed?

**Comment by ksvnix** [comment]
@gkorland, problem solved, thanks!
