### ISSUE TITLE
Allowed characters for index name

### ISSUE THREAD

**Issue by kkmuffme** [RediSearch/RediSearch#1676]
Which characters are allowed for a redisearch index name? Are there any that are not allowed?

**Comment by ashtul** [comment]
@kkmuffme , RediSearch does not have any limitation on the characters used for the index name.

The only limitation is the way strings are parsed in the C language. I have done some tests in which `"` gave me an error (since it symbols the beginning or the end of a string) and `\` (escape) gave me mixed results. So I would suggest to refrain from using these two characters and test any other special character to ensure it produces your expected result.

**Comment by ashtul** [comment]
@kkmuffme, I hope the answer solved the issue so I'm closing it.
