### ISSUE TITLE
Garbage collection doesnt work?

### ISSUE THREAD

**Issue by kkmuffme** [RediSearch/RediSearch#1770]
I have a redis instance, that runs redisearch for multiple (dev) websites.
For some reason, it seems that the garbage collection isn't working correctly, since the memory used is growing and growing, despite the data actually staying the same (pretty much)

I have a dump.rdb file I can provide privately to help debugging.

Since there was an issue earlier with GC (running too often & crashing the server), I now start redis with this command:

`/usr/bin/redis-server /etc/{{instance_name}}.conf --supervised systemd --daemonize no --loadmodule /usr/local/lib/redisearch.so FORK_GC_RUN_INTERVAL 900 FORK_GC_RETRY_INTERVAL 60 FORK_GC_CLEAN_THRESHOLD 10000`

I'm using redisearch 20001 on redis 6.0.9

EDIT: sorry fat-fingered on enter before writing the issue text.

**Comment by gkorland** [comment]
```
FORK_GC_RUN_INTERVAL 900 FORK_GC_RETRY_INTERVAL 60 FORK_GC_CLEAN_THRESHOLD 10000
```
Did you cross the 10000 garbage docs?
For how long did you run the test?
Do you see forked process? (the GC starts a forked process on each cycle)
Did you try to reduce the numbers and verify the GC is running?

**Comment by ashtul** [comment]
@kkmuffme 
I am afraid the rdb file won't help much since it does not contain the index itself and loading from it will reindex the documents without a need for GC. Can you try and confirm that dumping and reloading the index results in a smaller index? Can you please compare the GC stats on `FT.INFO`?

How what rate do you see the memory consumption grow? High? Low? Does the growth rate slow down?
 
One possible reason could be that inverted indexes are not deleted even if all documents which included a term get deleted (see #1263)

**Comment by kkmuffme** [comment]
Thanks, found the problem: someone tested and created loads of indices (+ indexed things on them), and then abandoned them (after deleting them). So we ended up with 100000s of inverted indexes left.

It's a bit awkward that redisearch creates some kind of (redis-cli) invisible, parallel structure which makes dev ops & admin work much harder, since we cannot see in redis-cli that there are redisearch data on that redis instance actually.

**Comment by ashtul** [comment]
@kkmuffme 
We have `FT._LIST` command.

**Comment by kkmuffme** [comment]
Yes, can be closed. I just needed some time to ensure it's working without issues now.
