### ISSUE TITLE
search nearby locations with AGGREGATE

### ISSUE THREAD

**Issue by syedappinventiv** [RediSearch/RediSearch#2040]
Hi, I used to get nearby location with FT.SEARCH like this `@location:[lon, lat, range, unit]` but i needed to calculate the distance the sort the results also hence i shifted to FT.AGGREGATE. I searched the docs and there is no Geo filter like this in APPLY as well as FILTER in AGGREGATE.
Is getting nearby locations possible with AGGREGATE?

**Comment by ashtul** [comment]
@syedappinventiv 
The filter `@location:[lon, lat, range, unit]` should work with FT.AGGREGATE. I have just confirmed it. What error do you get when you use it?

Another way on FT.AGGREGATE is to `LOAD` the field and then `APPLY` to it the `geodistance` function. This is more expensive since you have to load the field. (We have just added the option to make GEO fields SORTABLE (#2033), but it hasn't been officially released yet.

**Comment by ashtul** [comment]
@syedappinventiv do you need further help on this?

**Comment by syedappinventiv** [comment]
Hey @ashtul Thanks for your help, It did work.
