### ISSUE TITLE
Return Field not working on C#

### ISSUE THREAD

**Issue by vangxitrum** [RediSearch/RediSearch#3081]
I am using RedisJSON and RediSearch module for my ASP.NET project but I can't set ReturnField for my Query.
Here is my code:
  var query = new Query($"@plain_text:{{{SearchText}}}");
  query.SortBy = "offer_id";
  query.SortAscending = false;
  query.Limit((Page-1) * PageSize, PageSize);
  query.ReturnFields(new FieldName("$.id", "id"));
  var rs = (await _searchClient.SearchAsync(query)).Documents;
plz help

**Comment by shacharPash** [comment]
Hi, I tried to figure out what the error was but I couldn't figure out why it wouldn't work.
Anyway, a few things.
1. If you could send the monitor that shows exactly which commands were sent to Redis, it would be easier to debug the problem.
2. The RedisSearch client in .NET was written by StackExchange, so I would recommend writing the issue there and they will be able to easily identify whether the problem is in the client or in your code ([NRediSearch](https://github.com/StackExchange/NRediSearch)).
3. These days I am writing a project called NRedisStack which will contain all the modules, there are already commands for the modules: JSON, TimeSeries, Bloom. there are no Search commands yet but there will be soon, you are welcome to follow the progress and start using it now - [NRedisStack](https://github.com/redis/NRedisStack).

**Comment by vangxitrum** [comment]
tks
