### ISSUE TITLE
How to query tag fields for "any value"?

### ISSUE THREAD

**Issue by stevedh** [RediSearch/RediSearch#3272]
Is it possible to query a tag index for documents which have any values for a tag?  

For instance the results of executing  `ft.tagvals idx tagname`  and then running the query `ft.search idx @tagname:{val1 | val2}`

**Comment by oshadmi** [comment]
@stevedh Another alternative to what you have suggested could be to use a wildcard (starting with [2.6 GA (v2.6.3)](https://github.com/RediSearch/RediSearch/releases/tag/v2.6.3))
`ft.search idx "@tagname:{w'*'}" DIALECT 2`
But this requires fixing/merging PR #3279.
You can try a workaround
`ft.search idx "@tagname:{w'?*'}" DIALECT 2`

Another alternative would be less efficient since it will iterate all documents
`FT.AGGREGATE idx * LOAD 1 tagname FILTER 'exists(@tagname)'`
