### ISSUE TITLE
Suffix search - feature request

### ISSUE THREAD

**Issue by manishtoons** [RediSearch/RediSearch#331]
Would it be possible to add suffix search? (as fuzzy search already in place)

something like

`FT.SEARCH idx *redis`

It will be really useful.

**Comment by dvirsky** [comment]
It’s possible at the expense of a lot of ram. @itamarhaber you just save the terms reversed in the term trie or create an alternative trie for reversed terms so you will not expand them by mistake for fuzzy etc. it should be optional because most people will probably not want it but the cost is high.

**Comment by itamarhaber** [comment]
@dvirsky I knew the reversing trick, too bad there isn't something smarter and less expensive.

@manishtoons suffix search is a nice feature, but the memory cost is frightening. I suggest we keep this FT open to collect more inputs/get a consensus from the community. Makes sense?

**Comment by manishtoons** [comment]
Sure, thanks for the consideration!

Great work on 1.2.0! Congratulations guys!! and thank you for quick turnarounds for features and fixes.
