### ISSUE TITLE
Indexing JSON Document Keys with JSONPath Reserved Characters

### ISSUE THREAD

**Issue by Parthib** [RediSearch/RediSearch#3367]
I’m having a bit of trouble with my Redisearch + RedisJSON use case. My JSON documents can contain keys with characters considered special by the JSONPath syntax. For example, a document might be:

```
{
    “Distance(mi)”: 5
}
```

If I attempt to create an index on the JSONPath `$.Distance(mi)`, I get an exception:

```
redis.exceptions.ResponseError: Invalid JSONPath '$.Distance(mi)' in attribute 'Distance(mi)’
```

I assume this happens because parenthesis are reserved in the JSONPath syntax - https://redis.io/docs/stack/json/path/.

After reading this reference on escaping in RediSearch
https://redis.io/docs/stack/search/reference/escaping/
I thought maybe I could escape the parenthesis, but this did not work either:

```
redis.exceptions.ResponseError: Invalid JSONPath '$.Distance\(mi\)' in attribute 'Distance(mi)’
```

Is there a way to escape these reserved characters for my JSONPath when I create my index? 

Are JSON document keys with these special JSONPath-specific characters not possible to index with RediSearch? Keys without these special characters seem to work perfectly fine when creating indices!

**Comment by MeirShpilraien** [comment]
Please notice that using `(` or `)` on dot notation is very confusing because of the following scenario that uses filters:
```
$[?(5 == @.Distance(mi)]
```

How will you know if the last `)` is closing the bracket or its part of the phrase that you are trying to access. Also how would you know if its a function invocation (which are supported in json path but not yet supported by RedisJSON).

In any cases I recommend using bracket notation here: `$["Distance(mi)"]`
