### ISSUE TITLE
FILTER expression doesn't work on text fields having special characters

### ISSUE THREAD

**Issue by Aadit-Bhojgi** [RediSearch/RediSearch#3516]
It is mentioned in `RediSearch v2.6.7` documentation that we need to handle special characters by escaping them.
https://redis.io/docs/stack/search/reference/escaping/

It works fine when using in query:
`FT.AGGREGATE index '@id[1 1] @name:user\-1000' LOAD * SORTBY 2 @name ASC LIMIT 0 5`

but when we are doing search for strings having special characters in FILTER expression, it doesn't work at all:
`FT.AGGREGATE index '@id[1 1]' LOAD * FILTER "lower(@name) < lower('user\-1000')" SORTBY 2 @name ASC LIMIT 0 5`

As a workaround, can I achieve this without using FILTER expression instead?

**Comment by oshadmi** [comment]
@Aadit-Bhojgi 
The string literal `user\-1000` in the right-hand-side of the FILTER predicate is being [un-escaped](https://github.com/RediSearch/RediSearch/blob/e24ab70d5d33b15b07f6246c674368e02b026782/src/aggregate/expr/exprast.c#L52), while the name field on the left-hand-side does contain an escape character IIUC (and this is also related to #1304)

A workaround could be using some other character instead of the escape character, which has greater lexical ordering, e.g., `]` is greater than `\`, so this could work:
```
FT.CREATE index ON JSON SCHEMA $.id as id NUMERIC $.name as name TEXT
JSON.SET doc:3 $ '{"id":3, "name":"USER\\-3000"}'

FT.AGGREGATE index '@id:[1 3]' LOAD 1 @name FILTER 'lower(@name) <= lower("user]]-3000")' SORTBY 2 @name ASC LIMIT 0 5
```

Can you please share the index definition and a few hash/json documents?
