### ISSUE TITLE
[BUG] FT.SEARCH LIMIT issue

### ISSUE THREAD

**Issue by chenlizhao** [RediSearch/RediSearch#3777]
**Describe the bug**
when FT.SEARCH with large LIMIT number, such as 5 millions, then the redis server is crashed

**To Reproduce**
1. insert userIndex with more than 5 millions documents
2. search userIndex by FT.SEARCH command with LIMIT 5000000 10 to get one page content

**Expected behavior**
the redis server returns the result correctly

**Environment (please complete the following information):**
 - OS: centos7.9
 - Redis: 6.2.6
 - Version/branch 2.x

Is there alternative way to get page info as above?

**Comment by meiravgri** [comment]
Hi @chenlizhao 
I assume the server crashed due to memory overflow. The default behavior of ft.search is to add a sorter to the query pipeline. The sorter will accumulate all the results in order to sort them, skip the `offset` results and returns the next best `limit` results.
So in case you don't need a sorting phase, try running it with dialect 4, which excludes the sorter if it doesn't explicitly appear in the command. (see skip sorter in the below image taken from https://redis.io/commands/ft.search/)
![image](https://github.com/RediSearch/RediSearch/assets/109056284/b970a72d-cb7c-4023-9d9b-a50ea180bbb0)
Another option is to run the command with `ft.aggregate`, which doesn't include a sorter by default. 
Hope it helps

**Comment by chenlizhao** [comment]
@oshadmi Thanks for your suggestion!

**Comment by meiravgri** [comment]
I'm not @oshadmi, but no problem 😄

**Comment by chenlizhao** [comment]
@meiravgri Sorry, thank you again!

**Comment by oshadmi** [comment]
@chenlizhao Thank you for reporting.
Can you please share the redis log with the stack trace of the crash?
Which RediSearch version are you using?
Please note that returning large result sets with `FT.AGGREGATE` could also be related to #3494 (fixed in [2.6.9](https://github.com/RediSearch/RediSearch/releases/tag/v2.6.9))
