### ISSUE TITLE
Appending of `A/a` in text field search results in incorrect result [BUG]

### ISSUE THREAD

**Issue by PatrickPrakash** [RediSearch/RediSearch#4349]
**Describe the bug**
FT.SEARCH fails on TEXT index while appending a **A** or **a** in the end of the search term, in full text search.

**To Reproduce**
1. Create an index
`FT.CREATE auto ON JSON PREFIX 1 auto: SCHEMA $.name AS name TEXT`
2. Insert a value to the above indexed prefix
`JSON.SET auto:1 $ '{"name":"Ron Dan", "lastSeen":1478476800, "loggedOut": true}'`
3. Search using full text FT.Search
`FT.SEARCH auto @name:'Ron Dan a'`

**Expected behavior**
`FT.SEARCH auto @name:'Ron Dan a'` should not expected to return the _Ron Dan_ json data unlike when any other letter than a or A is appended.

`FT.SEARCH auto @name:'Ron Dan e'` does not returns the above results

**Environment (please complete the following information):**
 - OS: [Redis Cloud]
 - Redis Search : v2.6.12
 - RedisJSON : v2.4.7

**Comment by oshadmi** [comment]
@PatrickPrakash `a` is a [stopword](https://redis.io/docs/interact/search-and-query/advanced-concepts/stopwords/) and since it is skipped when indexing and when querying, the query `FT.SEARCH auto @name:'Ron Dan a'` matches `Ron Dan`
You can use the `STOPWORDS` keyword when creating the index to exclude `a` from the stop-word list and get the behavior you are expecting (notice it may increase index size and use more CPU when there are many occurrences of `a`)

**Comment by PatrickPrakash** [comment]
Thank you @oshadmi for the detailed brief. I knew it would be a optimization-related, but now it's clear.
