### ISSUE TITLE
[BUG] aggregation day function incorrect output

### ISSUE THREAD

**Issue by keithchew** [RediSearch/RediSearch#4393]
Testing on 2.8.11, but likely this bug has been around a lot longer.

Query to test the day() function:
```
ft.aggregate test-idx "*" APPLY day(@timestamp) AS day SORTBY 2 @day desc LIMIT 0 1
```

Returns:
```
1) "39"
2) 1) "timestamp"
   2) "1704118547"
   3) "day"
   4) "1704153600"
```

You can see above the day is the start of the next day instead of the current. This is for year 2024, but working for year 2023. Looking at the code, maybe a bug in the fast_timegm() function?

**Comment by GuyAv46** [comment]
Nice catch! Thanks for reporting.
I think a faster and simpler solution would be not to include the current year if it is a leap year, and to use `tm_yday` which counts the number of days from the beginning of the year including a leap day if there was one.
[here is a correction check for my solution, compared to the existing implementation](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1AB9U8lJL6yAngGVG6AMKpaAVxYMQAVgDspBwAyeAyYAHLuAEaYxN4ATKQADqgKhLYMzm4e3n5JKTYCQSHhLFExXvGWmNZpQgRMxAQZ7p6%2BFphW%2BQy19QSFYZHRcRZ1DU1ZrQojvcH9JYPlAJQWqK7EyOwcAKQaAILbe7EAzFg0IQDUQgAqOwBKl8aXAJIAsthnAJxcXlwAbD5c7x8ZwA9MCzlwAHSQgHvd77TZHE4zM7YUIAEQeLzeki4GiOPj%2BgJBYMO0NiENiGlh8N2CMOwWQbiwZ02h0c1gAnglMBCEKzsPCjgymZgWWybGxefzBfSGIzXMzWY5JvhUFLDgLabsJZhjAQzlQmJM9Xg2MAWBA0AxJmdJsRXNYzgQWGcAFS0Z0LFk%2BABC%2BzOxLO7SYCSU6DO6CYHIUZ1cgjoToQoqiwGCDGCwDOqCoQYAbtEOWcWLI%2BbsA1abcF9cWGMZI9HNl4/V40WLW5tfRpSGdSd2vO9u%2B8u%2BDKd2vlwxwAOCdnWJceKzySHbuxHzLnsaaQ9w6SDto1l%2BstnWgCTMEDmYeoKbsEevX4%2BX0Pd1wEZDGBDEBQHmk7APny%2Bfm2x7OgAtPyzrGBe9RnCBZw%2BBoB4BqCTosGBGoQVBxBnHgMZUMQqAugCGgaBC/oPiGMasq2ED/leLKxD6s5emCu6HIxAaBgwqBZjmISqPqBAAO7cbQMwxnGNi0GcmGzriJFkcheBARAHqoeBLCQQBLLYLEmyTgh7yHOCxHMcZCFsQpYL0BRMFUWcED2XgwKSAsrpGQijF4AiXiSGcCzfket5RpRhytjWdbBY2PqqWh2AQTWjb7hZWq/k6d70X6oXAWp6EaSw9YweCiGBul2ZFiWZwJEaYakYF6V2UF0YZfZtGAa6PY/F4XoeeRoYBXsR7EJgBCrAwLXpe1k4/JIJnNSpoHqe%2BKxYe1hw/LNPXzTlcV5cEbpnOt3UMdlsUQUoyD9XuP46nqBp4KoxiGsaOrmpaAg2naDoCS67qet6h6pchwahpg4bpRJCYEEmZwpmmGY8XmBblYIpapSeRhOph96Nfe1l9clA2pa1IWtjFi0ybB8HFchC25Zp0E4Qa%2BGEUO8lHnjJMtVjzVcKZrHsUhYJcQjfECcJx5ibG8ZSTJc7EbVhN/vVWVk3THL1v1SvBUBONzcT%2B1rV1zUc5dg3DaN43a5N00bcdW2nRpCDLQb60aEdjH24tLB7e1h3G7TO3GOdl0%2BPuKVVkWTB7RA3W%2BmRAafY6zoGiQLBMAQoOaxxKQAF66vqhp0M4ElZwGCTEFWVAQAisQgXX9cN43TcGkaBAmmaLpN133eNo4DA1/5BMcS3RcrIIQHmQDw/8FhNGmvnZzIKsQFXLc9xPK8iFL1hSoouimKb2xi/Lx5dkQOtrp%2B7HU/Dxx5o3cQ1exD82/dgiPwz2nGfoIPN%2B39hOYIAsAANY6ifh/VO6dQZejAGAOyT024vQtO/T%2BUCf7X3jv/DiyFy6VyfrEBB7dMDmhHvQdAIBe4EEod5Wg6Be791iAubev9MFYNIcXQQp8GKl1vldI8AY%2BGpTLhXQQVca6EKQaQ0G9EvA51cE6eeX4vB9xrt2QutAOEEBYfwyqIiCBiMYd3IxDcUQMHDBI%2BeJDjFd3oQPHhuDRH4OscYu6D0LEdxgs4hutjGHaKEewse%2Bo7KT0wTPFq89brbxXtcO4B8BRHyibvVEGIN7xMYok7hWVz4aEvm7Py/1WF3xYA/cBr96IQOIF/aBPDh54EASAsBKDIHfxgXArKNA3GtyIa9JplS0ELAwTothOC9EGIIfdR6XTJHqNBhQ5RVD5k0LocohhTDVh%2BLYdPKOGjAlcMyn/XhodMGCOHg4/R%2BCOmTOepYl0MzwzeTkQotgSiVGMLUdszRGyOJnLGV47upjzETPccQzuzifGxD8XuDgSxaCcC8LwTwHAtCkFQJwRwtplrrHoqSXgBBNDQqWMA7wkJJA%2BEMlNMlk5WbSFhRwSQvAWASGIqQRFyLUUcF4AoEAXY8VIuhaQOAsAYCIBQARBIdBojkEoGgFg4r6AxGQMALghx4g0A9NELlEAIj4tIBEYI9QOScB4Lq/VxAOQAHkIjaCqLy41Mq2CCHNQwWghq%2BWkCwBEVwwBHBiFoFy7gvAsBpyMOIN1%2BAhrVHzP65FmBVBVBfBsY1VZ2g6tEhEYgBrnBYB1QQCujKA1LCoAYYACgABqeBMCCXNdyRFxr%2BCCBEGIdgUgZCCEUCodQbrdATgMEYEAphjDmDTVyyASxUAJE6P6kC5rDi8FQPmYgFcsAjpjm0DoaR7BmLGJ4CcgQZjFFKHoXIqQBDbqPckE9DA%2BgHsGBOSo1QBDdFGC4Zoeh72dCfdMIoAwYh3qmGev9PRr0/okEsBQmLm0wrhQinV7KziqCmiBaaZxgDIGQOCQ4FJ7K4EICQbFvNcX4oGaQJMTAsAxFXUS0lEIfD6U%2BO8fSvxJDvBmjSzg9LSCMskOSLwXhSSfEkFStaXA/CsrnZwTl3LSC8q0EsQVIrY3xqIGQCgEB6gluUIYdoQgnaCVrbwGVcr05pE0yEWgOnUB6Z1YZiVCqlUqtIDZ%2BVoRWAbAM2K2z5qXwWas26xTyAdjEBLRJ/wcbkC1HwIi3g9bhCiHEC2mL7a1A6u7foQwJgzD6DwBEFdY6J1pH9ZyiDb7bzBFM9p3T%2BnSCCQzQkI1/LaXwpZbBzg2Awsvjwwhn4SHfKofQ8qrDEBHDdhw8p/DCxCN8uI6R8jlAoN0oZdkCEkhJA/H0pOb4GgfiHEnIcLbzW3XsskzyojhKQCCYhOULbyrKS4lhD8HtnBZ0HbZSFmTBL9CcFiDBw7b3TukAXSkOwkggA%3D%3D). Notice that I use `leaps = (tyears + 1) / 4;` to not include the current year, instead of `leaps = (tyears + 2) / 4;`
[And here is a performance comparison](https://quick-bench.com/q/oTV4_9uVqPTcrj2fpDEvbbMzZ48) of the fix, [and here compared to the standard function](https://quick-bench.com/q/2Bc8WY1Ys0vmbp-HPagWFxu81jI)

**Comment by GuyAv46** [comment]
Fixed. Available on master and version branches.
Will be part of `v2.6.16` and `v2.8.12`
