### ISSUE TITLE
[BUG] High insert/delete, index with filter expression gradual slowdown

### ISSUE THREAD

**Issue by keithchew** [RediSearch/RediSearch#4672]
Testing on v2.8.13, we have a program which does heavy insert and delete of keys.

With an index with filter expression, we found the ft.search to gradually slow down. Digging into this further, we believe we have found the reason. In spec.:
```
void Indexes_DeleteMatchingWithSchemaRules(RedisModuleCtx *ctx, RedisModuleString *key,
                                           RedisModuleString **hashFields) {
  SpecOpIndexingCtx *specs = Indexes_FindMatchingSchemaRules(ctx, key, ===> false <===, NULL);
...
```
Is there a reason why the runFilters is set to false on delete of a key? This means the index with filter expression will keep getting larger and larger without the removal of deleted keys, and eventually will run out of memory or slow down the queries.

We have changed the above to true to test, but if the theory above is incorrect, please advise so we can revert and continue tracking down this issue.

**Comment by meiravgri** [comment]
Hi @keithchew 
To better understand and diagnose the problem, could you please provide additional details, such as:

FT.INFO, example documents, and a detailed set of steps to reproduce the issue.

Regarding the `Indexes_DeleteMatchingWithSchemaRules` function, the `runFilters` parameter is set to false during key deletion because the document is intended to be entirely removed from the index, making the filter unnecessary.
However, if you have observed that memory usage increases unexpectedly 

If you have any additional evidence or observations of unexpected memory growth or performance issues, please share them.

Thanks!

**Comment by wernermorgenstern** [comment]
> hi @meiravgri
> 
> I have tracked it down. It is the GC which kicks in every minute. I am going to close this issue, as we have enough information to apply back-pressure to the rate of deletes and improve the overall performance.

Did you change a setting?
