### ISSUE TITLE
[BUG] Wrong Levenshtein distance results with %%

### ISSUE THREAD

**Issue by anindyasudhir** [RediSearch/RediSearch#4983]
**Describe the bug**
FT.SEARCH @name: %%Diane%% is giving results with names like Ines also. The double % sign is for levenshtein distance of 2 and Levenshtein distance between Diane and Ines is 3, so Ines should not be present in the results 

**To Reproduce**
1.Create hash data in redis with keys, name, address, phone number etc. insert data with names Diane, Diana, Ines, Ane etc
2. create an index on the hash schema
3. Write search query FT.SEARCH '@name: %%Diane%% '

**Expected behavior**
%% double percentage sign means the key would be fuzzy matched with Levenshtein distance of 2 but the results are showing results with edit distance of 3 as well.

**Environment (please complete the following information):**
 - RediSearch v.2.6.12
 - Redis browser workbench 

**Additional context**

**Comment by kei-nan** [comment]
Hi @anindyasudhir,

Due to "Ines" ending with an s I think it might be stemmed into an "Ine".
That could explain why it was matched for a levenshtein distance of 2.

Can you share the schema you used to create the index?
Alternatively can you add the `NOSTEM` flag to the name field in the index creation?

Please let us know if that solves your issue.

**Comment by anindyasudhir** [comment]
Hi @kei-nan, 

You were right, we added NOSTEM on the name field in the index and it fixed the problem.

Thanks, 
Anindya

**Comment by anindyasudhir** [comment]
The solution given by @kei-nan worked. Thanks
