### ISSUE TITLE
Option to rename/swap/alias an index.

### ISSUE THREAD

**Issue by gkorland** [RediSearch/RediSearch#575]
MOD-178

We need a feature to rename the schema (aka index) so we can load the data in a temp index while serving the requests using Live index. (classic swap)

Because, It takes longer to update the records during the nightly sync operations. Moreover during the records are updated, redis search queries times out until the update operation is complete. So, we are dropping the index and reloading from scratch. This is much faster but the data is not available while it's loaded again.

We can address the availability by loading the data into a temporary schema and SWAP it after dropping the Live Schema.

**Comment by mnunberg** [comment]
As you know, all our keys are prefixed by the name of the index. Because of this, the only way I see this working without renaming all the actual keys, is to have a central key within the DB that provides mappings between "common" index names and their actual keyspace entries..

Interface-wise, I am thinking something like:

```
FT.ALTER idx RENAME newname
```

Internals-wise, I am thinking about having a Redis key that contains the mapping between index name and the actual keyspace name. This could be a simple hashtable or similar. We might actually just save it, but always keep it in process memory (so there is no need to open two keys each time an index is accessed).

Regarding document access, the user should note that this provides no isolation between two indexes at the document level, but this is true anyway.
