### ISSUE TITLE
REPLACE (without PARTIAL) keeps old fields

### ISSUE THREAD

**Issue by sparzan** [RediSearch/RediSearch#647]
Expected lastName to be cleared when I run REPLACE without PARTIAL. did I miss something? This happens on both TEXT/NUMERIC and whether I use or don't use NOSTEM/SORTABLE.

```
127.0.0.1:6379> FT.CREATE foo STOPWORDS 0 SCHEMA firstName TEXT NOSTEM SORTABLE lastName TEXT NOSTEM SORTABLE
OK
127.0.0.1:6379> FT.ADD foo 1 1 FIELDS firstName John lastName Doe
OK
127.0.0.1:6379> FT.ADD foo 1 1 REPLACE FIELDS firstName John2
OK
127.0.0.1:6379> FT.GET foo 1
1) "firstName"
2) "John2"
3) "lastName"
4) "Doe"
```

**Comment by MeirShpilraien** [comment]
Hey @sparzan 
The REPLACE option only replace the data on the index and the  relevant fields on the hash, but it does not drop fields which already exists (and you did not provide a their value on the update command).
When you perform FT.GET you are getting the data from the hash and this is why you see all the fields, But if you try to search for `Doe` you will not find it:
```
127.0.0.1:6379> FT.SEARCH foo Doe
1) (integer) 0
```

**Comment by sparzan** [comment]
so this is intended? feels odd there's no 1:1 correlation between document stored and searched.

i guess i could either:
1. FT.DEL (with DD) and then do FT.ADD (no REPLACE)
2. or FT.SEARCH instead of FT.GET

unless this is by design?

**Comment by MeirShpilraien** [comment]
The reason is that it allows you to save additional fields in the hash which are not index and we obviously do not want to delete you data. It might be possible to delete only indexed field, we will consider.

Until then the two workarounds you listed will work. I would suggest the first one cause this is actually what we are doing on updates (delete + add), and if you already have the docid then there is no point of issuing a search query.

**Comment by ashtul** [comment]
Please see #2004
