### ISSUE TITLE
Allow to delete rows with query

### ISSUE THREAD

**Issue by lipoiq** [RediSearch/RediSearch#904]
When will this opportunity be as in MySQL?

**For example in MySQL:**
```DELETE FROM table_name WHERE column1 = 'redis'```

**For example for RediSearch:**
```FT.DEL index_name @title|description:"mysql" [DD]```

**Comment by MeirShpilraien** [comment]
@lipoiq You are not the first to ask for this feature, we hope to have it soon. Till then you might want to try another approach, you can try using redisgears (https://github.com/RedisGears/RedisGears) to achieve what you want. Basically you just need to write a python script that reads the relevant docs from redisearch and deleted them one by one. Small thing to notice is that you need to use redisearch in a safemode otherwise the queries will run in background thread and you will not get a replies in redisgears script.

Let me know if you do decide to go with this approach, I can guide you on how to do it.

**Comment by lipoiq** [comment]
> @lipoiq You are not the first to ask for this feature, we hope to have it soon. Till then you might want to try another approach, you can try using redisgears (https://github.com/RedisGears/RedisGears) to achieve what you want. Basically you just need to write a python script that reads the relevant docs from redisearch and deleted them one by one. Small thing to notice is that you need to use redisearch in a safemode otherwise the queries will run in background thread and you will not get a replies in redisgears script.
> 
> Let me know if you do decide to go with this approach, I can guide you on how to do it.

Can u help me? I use PHP

**Comment by MeirShpilraien** [comment]
You are using the oss version right? Do you have RedisGears installed? If not follow this https://oss.redislabs.com/redisgears/quickstart.html#build. Let me know when you have RedisGears and RediSearch up and running. For any issues let me know.

**Comment by gkorland** [comment]
Duplicate #587
